### ISSUE TITLE
Update mirrors DB

### ISSUE THREAD

**Issue by rgaudin** [kiwix/mirrors-qa#12]
We need to initialize our DB (#6) with mirrors information and we'll also need to update them periodically.
For this, we should rely on the online list of mirrors that we have.

https://download.kiwix.org/mirrors.html

It's in HTML format but all information can be extracted easily.

Let's use the URL's hostname as ID for now and also assume that any DB mirror not found in the page should be marked disabled

**Comment by elfkuzco** [comment]
So, which means I should remove the `BaseURL` field for `Mirror` model?

**Comment by elfkuzco** [comment]
What do you think about providing a command line interface for this?

```
backend update-mirrors 
```

This way, it can be run externally by an admin or scheduled to be run periodically via cron

**Comment by elfkuzco** [comment]
Perhaps, in the code, it can check if there are any rows in the table. If there are none, it will involve the function behind the CLI. Subsequent updates would be done externally or via a scheduler
