### ISSUE TITLE
Questions for Dashboard Development

### ISSUE THREAD

**Issue by elfkuzco** [kiwix/mirrors-qa#23]
In order to build a dashboard that accurately gives insights on the results of the speedtest, it is important to ask the right questions before building the chart to answer the question.

Currently, here are some of the questions I have come up with:

- What is the status distribution for tests per mirror?
- What is the maximum speed from each test country across all the mirrors?
- What is the minimum speed from each test country across all the mirrors?
- What is the average latency of requests from a test country across all the mirrors?
- Which ISP offers the maximum/minimum speeds?

NOTE: These questions allow for optional filtering based on worker ID.

Below is a sample anwering the first two questions.

![Screenshot_20240724_162456](https://github.com/user-attachments/assets/70999fb8-57e5-4ba3-a4c5-aae01bcd2185)

**Comment by rgaudin** [comment]
Thank you ; from the initial requirements, I think there are only a couple of questions we want this tool to answer:

- is everything OK?
- help with slow download investigation
- where are we slow to download from?

## Is everything all right?

Are all mirrors performing as expected?
Given there is no expressed expectation, the expectation is that the mirror performs as it usually does.

### Difference between median and _current_ speeds

This shows the median speed for each mirror excluding the _Current_ interval. It also shows next to each the average speed for the _Current_ interval.

That current interval needs to be defined. Maybe 24h?

### Actionnable list

List of mirrors from the above data for which the difference between median and current is above a certain threshold (30%?)

This list should usually be empty. If not, there's degraded perf with a mirror that can be investigated.

## Why is my download slow?

Should we get a report of download being slow, after user has confirmed (via a speedtest) that his connection is OK, we want to know what are the historical data for the related mirror (if know) and/or the country

### Country Profile

- min/max/avg/median for all mirrors, from a selected country
- graph of tests speed

### Mirror Profile

- min/max/avg/median for all countries, to a selected mirror
- graph of tests speed

### Mirror/Country profile

- min/max/avg/median for a selected country to a selected mirror
- graph of tests speed

### Browseable data (table)

Basically access to human-friendly data of Tests with filters for country, mirror, worker and _period_ (date? interval?)

## Which countries are slow to download from?

- If some countries are slow on some mirrors, we just have to make sure those are not offered (mirrorbrain config)
- If some countries are slow no matter the mirror, we need to find/create a mirror in the region.

### List country/mirror mapping with median speed lower than a value (5mbps?)

Allow filtering by period

### Country/Mirror matcher

Allow filtering by period

Sorted list of median speed for a country over all mirrors ; limiting to a number of mirror per country (5?).
This would be the best match of mirror for a source country.
This may help us configure mirrorbrain differently.

----

That's what I can think of. Please question those. @kelson42 @Popolechien your feedback is requested

**Comment by Popolechien** [comment]
No specific comment as it is a bit above my intellectual paygrade. I would however be interested in having some sort of flag if a country/region suddendly drops.

**Comment by kelson42** [comment]
On my side, and sorry if this comes back on a decision which has already been made, but I challenge the idea of using a custom dev for this. I would really prefer to use a pre existing datalake/business intelligence solution.

**Comment by rgaudin** [comment]
> On my side, and sorry if this comes back on a decision which has already been made, but I challenge the idea of using a custom dev for this. I would really prefer to use a pre existing datalake/business intelligence solution.

This is metabase.We've agreed on this long ago.

> 
> In addition, the question which is how to reconfogure mirrorbrain based on stats? is more important to me than the dashboard.

This is not in the scope of the GSOC.
I find it strange to suggest reconfiguring MB automatically. without insight from observed data over a period of time.

**Comment by kelson42** [comment]
> > On my side, and sorry if this comes back on a decision which has already been made, but I challenge the idea of using a custom dev for this. I would really prefer to use a pre existing datalake/business intelligence solution.
> 
> This is metabase.We've agreed on this long ago.

Perfect then on the tech side!
