### ISSUE TITLE
Generate mirrobrain-config-friendly table

### ISSUE THREAD

**Issue by rgaudin** [kiwix/mirrors-qa#39]
As a first step towards automatically re-configuring mirrorbrain (that we dont want at the moment!), we want to output the data that would go into that configuration. It will be used manually for now.

It should be a simple list/table with an entry for each mirror:

- `ID`
- `region`
- `country`
- `regionOnly`
- `otherCountries`
- `score`

---

- `ID`, `region` and `country` are static
- `regionOnly` is set to `TRUE` unless specified otherwise below
- `otherCountries` is not set unless for redirected regions. In this case it's a comma-separated list of all countries in both regions.
  - `sa` redirects to `na`
  - `oc` redirects to `as`
- score is set to the rounded median speed over that mirror for its target (countries in its region – or regions for america)
- `mirror.kiwix` set global (no `regionOnly`) with a score of `100`
- `md.mirrors.hacktegic.com` is statically set global (no `regionOnly`) with a score of `100`

This follows the recommendation in https://github.com/kiwix/container-images/issues/263. We use two _fallback_ mirrors (kiwix and macedonia) as both have decent, stable speeds and mirror everything.

Looking at https://www.submarinecablemap.com/, we assume that South American users (where we have no mirror) would benefit from being served by North American mirrors. Same for Oceania and Asia. Africa is trickier as Eastern countries might be better served by Indian mirror while the rest would probably be better served by Europe. Let's us the fallback for now (in Europe) and revisit in the future, maybe we better from-african data.

For reference, here's the list of regions

| Code | Name |
| --- | --- |
| `af` | Africa |
| `an` | Antartica |
| `as` | Asia |
| `eu` | Europe |
| `na` | North America |
| `oc` | Oceania |
| `sa` | South America |

| Mirror | Region | Country
| --- | --- | --- |
| `fau.de` | `eu` | `de` |
| `dotsrc.org` | `eu` | `dk` |
| `your.org` | `na` | `us` |
| `mirrorservice.org` | `eu` | `gb` |
| `nluug.nl` | `eu` | `nl` |
| `mirror.accum.se` | `eu` | `se` |
| `laotzu-mirror.accum.se` | `eu` | `se` |
| `md.mirrors.hacktegic.com` | `eu` | `md` |
| `wikimedia` | `na` | `us` |
| `mirror.kiwix` | `eu` | `fr` |
| `mirror-sites-ca.mblibrary.info` | `na` | `ca` |
| `mirror-sites-fr.mblibrary.info` | `eu` | `fr` |
| `isoc.org.il` | `eu` | `il` |
| `mirror-sites-in.mblibrary.info` | `as` | `in` |

**Comment by elfkuzco** [comment]
Will there be a CLI entrypoint for updating the mirror's `otherCountries` and other mirrorbrain metadata? I think it's the better way of altering the Mirror metadata in the db. What do you think?

**Comment by rgaudin** [comment]
Sure but what would it look like? I dont want to manually pull this list of countries and pass it to a CLI.

**Comment by elfkuzco** [comment]
> Sure but what would it look like? I dont want to manually pull this list of countries and pass it to a CLI.

Something like `update-mirror <mirror-id> --regions=sa,na`

**Comment by rgaudin** [comment]
Sounds good. I think it could also update `--region` and `--country` as well.

**Comment by elfkuzco** [comment]
Um, I have created the query that generates this. It's a little bit complex and I had to use a couple of secondary tables and CASE expressions to set defaults. I tried documenting what happens in each branch in case you want to take a look and give me a feedback on it.

**Comment by rgaudin** [comment]
Thank you ; it looks very good and the comments are useful. I believe we can close the ticket, right?

**Comment by elfkuzco** [comment]
Yes.
