### ISSUE TITLE
Decide on a VPN provider

### ISSUE THREAD

**Issue by rgaudin** [kiwix/mirrors-qa#4]
Criteria:

- offers wireguard (modern protocol we'll instrument)
- good connectivity (reputation)
- has a large number of server locations
- server locations includes areas of interest to us:
  - where we think we have a large user base
  - where we lack mirrors
  - ➡️ mostly South-East Asia & Africa

I've already identified [Mullvad](https://mullvad.net) for which we paid for 6months for development:
- 684 servers in 44 countries [full list](https://mullvad.net/en/servers)
- Includes Hong Kong, Indonesia, Singapore, South Africa and Thailand
- we can retrieve the servers via [an API](https://api.mullvad.net/app/v1/relays)
- it's whats best in terms of privacy
- cost is fixed, stable and affordable: $5/mo.

**Comment by rgaudin** [comment]
[NordVPN](https://nordvpn.com/servers/) is not on the same ethics level as Mullvad but if that doesn't matter, is has servers in 111 countries.

<img width="277" alt="Screenshot 2024-05-29 at 15 51 02" src="https://github.com/kiwix/mirrors-qa/assets/57929/a195b921-cb10-4a60-bac5-de6227827c16">

**Comment by rgaudin** [comment]
We're using mullvad for now

**Comment by rgaudin** [comment]
Now that we are getting data ; we find mullvad's 44 countries to be limited. @Popolechien @kelson42 please list the countries you want and then we'll try to find a provider

**Comment by Popolechien** [comment]
Russia, China, Bangladesh, India, Pakistan, Iran, Turkey, Jordan, Yemen, Iraq, Egypt, Nigeria, DRC, Sudan, Cuba, Peru, Mexico

**Comment by rgaudin** [comment]
OK, here's a list of 38 VPN providers. The wireguard criteria is mandatory. I mentioned (at the bottom) some that are not compatible just so we don't look into them again

| VPN | Wireguard | Countries | Russia | China | Bangladesh | India | Pakistan | Iran | Turkey | Jordan | Yemen | Iraq | Egypt | Nigeria | DRC | Sudan | Cuba | Peru | Mexico |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | ---| --- | --- | --- |
| [Mullvad](https://mullvad.net/en/servers)/Mozilla | ✅ | 45 | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ✅ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ✅ |
| [Surfshark](https://surfshark.com/servers) | ✅ | 100 | ❌ | ❌ | ✅ | ✅ | ✅ | ❌ | ❌ | ❌ | ❌ | ❌ | ✅ | ✅ | ❌ | ❌ | ❌ | ✅ | ✅ |
| [IP Vanish](https://www.ipvanish.com/servers/) | ✅ | 55 | ❌ | ❌ | ❌ | ❌ | ✅ | ❌ | ✅ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ✅ | ✅ |
| [Cyber Ghost](https://www.cyberghostvpn.com/vpn-server) | ✅ | 55 | ❌ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ❌ | ❌ | ❌ | ✅ | ✅ | ❌ | ❌ | ❌ | ✅ | ✅ |
| [Private VPN](https://privatevpn.com/why-privatevpn/server-locations) | ✅ | 63 | ❌ | ❌ | ❌ | ✅ | ❌ | ❌ | ✅ | ❌ | ❌ | ❌ | ❌ | ✅ | ❌ | ❌ | ❌ | ✅ | ✅ |
| [Private Internet Access](https://www.privateinternetaccess.com/vpn-server) | ✅ | 91 | ❌ | ✅ | ✅ | ✅ | ❌ | ❌ | ✅ | ❌ | ❌ | ❌ | ✅ | ✅ | ❌ | ❌ | ❌ | ✅ | ✅ |
| [StrongVPN](https://strongvpn.com/locations/) | ✅ | 30 | ❌ | ❌ | ❌ | ✅ | ❌ | ❌ | ✅ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ✅ | ✅ |
| [Proton VPN](https://protonvpn.com/vpn-servers) | ✅ | 112 | ✅ | ❌ | ✅ | ✅ | ✅ | ❌ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ❌ | ✅ | ❌ | ✅ | ✅ |
| [NordVPN](https://nordvpn.com/servers/) | ✅ | 111 | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ✅ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ |
| [Xeovo](https://status.xeovo.com/) | ✅ | 16 | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ |
| [IVPN](https://www.ivpn.net/en/status/) | ✅ | 38 | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ✅ | ❌ |
| [AzireVPN](https://www.azirevpn.com/service/servers#locations) | ✅ | 26 | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ |
| [OVPN](https://www.ovpn.com/en/network) | ✅ | 32 | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ |
| [VyprVPN](https://www.vyprvpn.com/server-locations) | ✅ | 0 | ✅ | ❌ | ❌ | ✅ | ✅ | ❌ | ✅ | ❌ | ❌ | ❌ | ✅ | ❌ | ❌ | ❌ | ❌ | ❌ | ✅ |
| [TorGuard](https://torguard.net/anonymous-vpn/) | ✅ | 50 | ❌ | ❌ | ❌ | ✅ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ✅ |
| [WindScribe](https://windscribe.com/features/large-network/) | ✅ | 69 | ✅ | ❌ | ❌ | ✅ | ❌ | ❌ | ✅ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ✅ | ✅ |
| [VPN.ac](https://vpn.ac/status) | ✅ | 21 | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ✅ |
| [PureVPN](https://www.purevpn.com/servers) | ✅ | 65 | ✅ | ✅ | ❌ | ✅ | ❌ | ❌ | ✅ | ❌ | ❌ | ❌ | ✅ | ✅ | ❌ | ❌ | ❌ | ❌ | ❌ |
| [PrivadoVPN](https://privadovpn.com/what-is-a-vpn/servers/) | ✅ | 49 | ✅ | ❌ | ❌ | ✅ | ❌ | ❌ | ✅ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ✅ |
| [Tunnelbear](https://www.tunnelbear.com/features) | ✅ | 46 | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ✅ | ❌ | ❌ | ❌ | ✅ | ✅ |
| [hide.me](https://hide.me/en/network) | ✅ | 0 | ❌ | ❌ | ✅ | ❌ | ❌ | ❌ | ✅ | ❌ | ❌ | ❌ | ✅ | ❌ | ❌ | ❌ | ❌ | ✅ | ✅ |
| [CactusVPN](https://www.cactusvpn.com/vpn-server-locations/) | ✅ | 25 | ❌ | ❌ | ❌ | ✅ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ |
| [ExpressVPN](https://www.expressvpn.com/vpn-server) | ❌ | 105 | ❌ | ❌ | ✅ | ✅ | ✅ | ❌ | ✅ | ❌ | ❌ | ❌ | ✅ | ❌ | ❌ | ❌ | ✅ | ✅ | ✅ |
| [Ivacy](https://www.ivacy.com/vpn-servers/) | ❌ | 100 | ✅ | ✅ | ❌ | ✅ | ❌ | ❌ | ✅ | ❌ | ❌ | ❌ | ✅ | ✅ | ❌ | ❌ | ❌ | ❌ | ❌ |
| [Trubo VPN](https://turbovpn.com/vpn-server) | ❌ | 111  | ✅ | ✅ | ❌ | ❌ | ✅ | ✅ | ✅ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ✅ |
| [Panda VPN](https://pandavpnpro.com/server-details) | ❌ | 80  | ❌ | ❌ | ✅ | ✅ | ✅ | ❌ | ❌ | ✅ | ❌ | ✅ | ✅ | ✅ | ❌ | ❌ | ❌ | ✅ | ✅ |
| [Hide My Ass](https://www.hidemyass.com/servers) | ❌ | 210 | ❌ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| [ZoogVPN](https://zoogvpn.com/network/) | ❌ | 55  | ✅ | ❌ | ❌ | ✅ | ✅ | ❌ | ✅ | ❌ | ✅ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ✅ | ✅ |
| [Robo VPN](https://www.robovpn.com/servers) | ❌ | 16 | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ |
| [Virtual Shield](https://virtualshield.com/features) | ❌ | ?  | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? |
| [Fast VPN](https://www.namecheap.com/vpn/vpn-for-linux/) | ❌ | ?  | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? |
| [Avast SecureLine VPN](https://www.avast.com/secureline-vpn#mac) | ❌ | ?  | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? |
| [Perfect Privacy](https://www.perfect-privacy.com/en/serverstatus) | ❌ | 23  | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? |
|  [Malwerebytes VPN](https://www.malwarebytes.com/lp/sem-privacy/en) | ❌ | ?  | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? |
|  [AVG Secure VPN](https://www.avg.com/en-ww/download-secure-vpn-mac) | ❌ | ?  | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? |
|  [F-Secure VPN](https://www.f-secure.com/en/vpn) | ❌ | ?  | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? | ? |


From this it's very clear that the widest access is HMA which has crazy coverage. All our list but Russia. It even has servers in 🇲🇱 ! Unfortunately it's not compatible.

The best compatible one is the 🇨🇭 ProtonVPN which only lacks Iran, DRC and Cuba in our list. It also includes a lot of less common countries which are of interest to us.

@Popolechien the 1 year plan is 60CHF.

**Comment by Popolechien** [comment]
@rgaudin So be it. Should I just go over to ProtonVPN and subscribe for the 1-year plan? (meaning, there's no particular option to be aware of)?
![Screenshot 2024-08-20 at 14 34 13](https://github.com/user-attachments/assets/39589c4d-b864-41ac-a4cf-5b231d748d89)

**Comment by rgaudin** [comment]
That's the one
