### ISSUE TITLE
Performance Matrix

### ISSUE THREAD

**Issue by rgaudin** [kiwix/mirrors-qa#40]
Because we are now to configure mirrorbain for regions (#38 and #39), we need to be able to extract some data by region. This assume that the region and score data are all in the database.

We thus need the following (to be discussed) **Performance Matrix**

It's important we're able to tell whether this new mirrorbain configuration (serving per-region with 2 fallback mirrors) is an improvement over the current configuration.

For this we need a way to measure the service's performance. That is; what are the speed people are expected to get when downloading from us?

To get closer to reality (which we cannot measure), we have to get closer to how mirrorbrain decides which mirror to direct each requests to.

Here's thus the simplified mirrorbrain algorithm we'll be mimicking:

```py
all_mirrors = [...mirrors]
same_country_mirrors  = [mirror for mirror in all_mirrors if mirror.country == request.country]
same_region_mirrors = [mirror for mirror in all_mirrors if mirror.region == request.region]
if same_country_mirrors:
   return sorted_by_score(same_country_mirrors)[0]
if same_region_mirrors:
   return sorted_by_score(same_region_mirrors)[0]
return sorted_by_score(all_mirrors)[0]
```

That `sorted_by_score` would return a mirror `x%` of the time with `x` being based on the score.

The output of this would be a table with a row per mirror and a column per country (or the opposite) each giving the median download speed. In addition to a column per country, we'd need one column per region.

What's important here is that we dont use the `Test` table directly (that we already have) but weight all tests based on that algorithm.

---

Once this ticket is implemented, the output of this matrix will be our **baseline data**.
Once we're happy with our baseline data, we'll update mirrorbrain config (recording the date) and let the tests run for a while (at least a month) then we can reprocess the performance matrix and compare the results with the baseline.

## Baseline examples

If I want to look at results for France, I know it's gonna be simple because France has a mirror (2 actually) so there will be data only for 2 mirrors. On them, 96% of the tests will be using kiwix mirror (score is `3000` ATM) and 4% the mblibrary-fr one (score is `100`). *How we compute the weighted speed is open for discussion: we can either pick x% of the test and median those of pick the general median and weight using the percentage.*

Another example is India. With a single mirror, there will be only one matching row and that value will be the median of in-mirror from India.

If I look at a mirror instead of a country, say `fau.de` mirror line, it will have values for most countries because there is no `onlyXX` parameter set in mirrobrain at the moment so any Test not from a country which has its own mirror has a 14% chance of being assigned to fau.de and thus use its speed.

## Future examples

After https://github.com/kiwix/container-images/issues/263, results should be significantly different (whether this requires code change to build this matrix is TBD):

Results for countries with a mirror should be somewhat similar to the baseline as this is still prioritized. New scores will play a big role though.

Countries in EU, North America and Asia should not change much as they have a mirror in their region. Score would also play a role. Countries in South America on the other hand should change much. Africa and Oceania as well

If I look at a mirror, say `fau.de` mirror line, it will have values for many European countries because there are plenty of European countries but not a mirror in each. There should not be results for France, UK, Denmark, Sweden, Moldova and Israel because each have a mirror. There should not be any result from outside EU neither because fau.de will have the `onlyRegion` flag set.

Only the kiwix mirror and the moldova one will have results for countries in region where there is no mirror (africa, oceania)

**Comment by elfkuzco** [comment]
> What's important here is that we dont use the Test table directly (that we already have) but weight all tests based on that algorithm.

Could you provide more insights on how to _weight all tests based on the algorithm_?
