### ISSUE TITLE
create-countries should stop without input

### ISSUE THREAD

**Issue by rgaudin** [kiwix/mirrors-qa#44]
When the script is called without any argument, there is no output and the process stalls forever.

If there is no stdin upon start, we should assume it was not piped and show an error

```sh
mirrors-qa-backend create-countries
```

**Comment by elfkuzco** [comment]
Um, it doesn't stall per say. Rather it waits for input which can come from stdin. It allows me to type a list of strings (even though it's not something I would do). 

I imagine it to be like any of the Linux command utilities, for example `cat` that take input.

Of course, I can always refactor it. What do you think?

**Comment by rgaudin** [comment]
We want our scripts to be self-documenting, especially in this context of a sub command for which there are many with similar names. Our workflow here is **very far** from that of core unix tools. 99% of the time, we'll have a file on filesystem to work from. We should work toward that use case first

**Comment by elfkuzco** [comment]
Oh, okay.
