### ISSUE TITLE
Impossible to run all tests

### ISSUE THREAD

**Issue by rgaudin** [kiwix/mirrors-qa#54]
Ever since we moved to ProtonVPN, we have not been able to run all the tests.

ProtonVPN has 111 countries and we test on 13 mirrors. We are thus creating 1,443 (111 * 13) test requests everyday.
Everyday, we are able to complete about 800 tests (accounting for ~40GB) then we cannot make any new connection for many hours.

It's possible this intensive usage is not permitted by ProtonVPN (we are using VPN Plus plan). A ticket has been opened with ProtonVPN. Awaiting a response.

**Comment by benoit74** [comment]
Nice explanation, looking forward for the solution ^^

**Comment by rgaudin** [comment]
Yesterday's tests showed that the issue lied in our _connection-health_ check (to Mullvad's https://am.i.mullvad.net/ endpoint) that were failing after a number of calls, giving the script the information that connection was off and thus preventing it from running the tests.

Changing the URL of the check to ProtonVPN's https://ip.me did not exhibit this behavior and so all tests could run.

Fixed by f9f8319f736f9c79684a67f658bcc6a1da73938c
